spring:
  datasource:
    hikari:
      minimum-idle: 2
      initialization-fail-timeout: 0
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true

logging:
  level:
    root: WARN
    com.thegamersstation.marketplace: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

messaging:
  ably:
    enabled: true
otp:
  isEnabled: true